<?php
/**
 * Controller handles the all request of which is generated by the user activity in the
 * project
 */
require('Controller.php');
?>
<html>
    <head>
        <title>Twitter</title>
        <?php
       
        require('config.php');
        ?>
    </head>
    <body background="image/Website-Background.jpg" >
    <img src="image/birds.png" width="600px" >
        <div class="text-center" id= "body">
            <?php
            if (isset($_SESSION['login_url']) && !isset($_SESSION['data'])) {
                $login_url = $_SESSION['login_url'];
                ?>
                <div class= "login-btn">
                    <a href='<?php echo $login_url; ?>'>
                        <button type="button" class="btn btn-primary btn-lg">
                            <i class="fa fa-twitter">   Twitter    <img src="image/lock-white-padlock-md.png" height="30px"> </i>
                            </button>
                    </a>
                </div>
                <?php
            } else {
                header('Location:home.php');
            }
            ?>
        </div>
    </body>
</html>
